pylint:
    disable:
        # We use this a lot (e.g. via document._meta)
        - protected-access

    options:
        additional-builtins:
            # add long as valid built-ins.
            - long

pyflakes:
    disable:
        # undefined variables are already covered by pylint (and exclude long)
        - F821

ignore-paths:
    - benchmark.py
