[tox]
min_version = 4.0
requires = tox-uv
envlist =
    py{310,311,312,313,314}-mg{414,415,416,417}

[testenv]
package = wheel
runner = uv-venv-runner
dependency_groups = test
setenv =
    COVERAGE_FILE = .coverage.{envname}

commands =
    pytest --cov-report= --cov=mongoengine  tests/ {posargs}

deps =
    mg414: pymongo>=4.14,<4.15
    mg415: pymongo>=4.15,<4.16
    mg416: pymongo>=4.16,<4.17
    mg417: pymongo>=4.17,<4.18
