[tox]
envlist =
    py{310,311,312,313,314}-{mg4130,mg4140,mg4150}
skipsdist = True

[testenv]
commands =
    pytest tests/ {posargs}

deps =
    -rrequirements-dev.txt

    mg4130: pymongo>=4.13,<4.14
    mg4140: pymongo>=4.14,<4.15
    mg4150: pymongo>=4.15,<4.16   # includes >= 4.15.4

setenv =
    PYTHON_EGG_CACHE = {envdir}/python-eggs