[tox]
envlist =
    pypy3-{mg480,mg4101,mg4141,mg4155,mg4160,mg4170}
    py{310,311,312,313,314}-{mg480,mg4101,mg4141,mg4155,mg4160,mg4170}
skipsdist = True

[testenv]
commands =
    pytest tests/ {posargs}
deps =
    -rrequirements-dev.txt
    mg480: pymongo>=4.8,<4.9
    mg4101: pymongo>=4.10,<4.11
    mg4141: pymongo>=4.14,<4.15
    mg4155: pymongo>=4.15,<4.16
    mg4160: pymongo>=4.16,<4.17
    mg4170: pymongo>=4.17,<4.18
setenv =
    PYTHON_EGG_CACHE = {envdir}/python-eggs
