# mypy: enable-error-code="var-annotated"
from datetime import date, datetime
from decimal import Decimal
from typing import Optional

from typing_extensions import assert_type

from mongoengine import Document, EmbeddedDocument
from mongoengine import fields


def test_it_uses_correct_types() -> None:
    class Image(EmbeddedDocument):
        pass

    class Doc(Document):
        stringfield = fields.StringField()
        urlfield = fields.URLField()
        emailfield = fields.EmailField()
        intfield = fields.IntField()
        longfield = fields.LongField()
        floatfield = fields.FloatField()
        decimalfield = fields.DecimalField()
        booleanfield = fields.BooleanField()
        datetimefield = fields.DateTimeField()
        datefield = fields.DateField()
        complexdatetimefield = fields.ComplexDateTimeField()
        embeddeddocumentfield = fields.EmbeddedDocumentField()
        objectidfield = fields.ObjectIdField()
        genericembeddeddocumentfield = fields.GenericEmbeddedDocumentField()
        dynamicfield = fields.DynamicField()
        listfield = fields.ListField()
        sortedlistfield = fields.SortedListField()
        embeddeddocumentlistfield = fields.EmbeddedDocumentListField()
        dictfield = fields.DictField()
        mapfield = fields.MapField()
        referencefield = fields.ReferenceField()
        cachedreferencefield = fields.CachedReferenceField()
        lazyreferencefield = fields.LazyReferenceField()
        genericlazyreferencefield = fields.GenericLazyReferenceField()
        genericreferencefield = fields.GenericReferenceField()
        binaryfield = fields.BinaryField()
        gridfserror = fields.GridFSError()
        gridfsproxy = fields.GridFSProxy()
        filefield = fields.FileField()
        imagegridfsproxy = fields.ImageGridFsProxy()
        improperlyconfigured = fields.ImproperlyConfigured()
        imagefield = fields.ImageField()
        geopointfield = fields.GeoPointField()
        pointfield = fields.PointField()
        linestringfield = fields.LineStringField()
        polygonfield = fields.PolygonField()
        sequencefield = fields.SequenceField()
        uuidfield = fields.UUIDField()
        enumfield = fields.EnumField()
        multipointfield = fields.MultiPointField()
        multilinestringfield = fields.MultiLineStringField()
        multipolygonfield = fields.MultiPolygonField()
        geojsonbasefield = fields.GeoJsonBaseField()
        decimal128field = fields.Decimal128Field()

    doc = Doc()

    assert_type(doc.stringfield, Optional[str])
    assert_type(doc.urlfield, Optional[str])
    assert_type(doc.emailfield, Optional[str])
    assert_type(doc.intfield, Optional[int])
    assert_type(doc.longfield, Optional[int])
    assert_type(doc.floatfield, Optional[float])
    assert_type(doc.decimalfield, Optional[Decimal])
    assert_type(doc.booleanfield, Optional[bool])
    assert_type(doc.datetimefield, Optional[datetime])
    assert_type(doc.datefield, Optional[date])
    assert_type(doc.complexdatetimefield, Optional[str])
    assert_type(doc.embeddeddocumentfield, Optional[str])
    assert_type(doc.objectidfield, Optional[str])
    assert_type(doc.genericembeddeddocumentfield, Optional[str])
    assert_type(doc.dynamicfield, Optional[str])
    assert_type(doc.listfield, Optional[str])
    assert_type(doc.sortedlistfield, Optional[str])
    assert_type(doc.embeddeddocumentlistfield, Optional[str])
    assert_type(doc.dictfield, Optional[str])
    assert_type(doc.mapfield, Optional[str])
    assert_type(doc.referencefield, Optional[str])
    assert_type(doc.cachedreferencefield, Optional[str])
    assert_type(doc.lazyreferencefield, Optional[str])
    assert_type(doc.genericlazyreferencefield, Optional[str])
    assert_type(doc.genericreferencefield, Optional[str])
    assert_type(doc.binaryfield, Optional[str])
    assert_type(doc.gridfserror, Optional[str])
    assert_type(doc.gridfsproxy, Optional[str])
    assert_type(doc.filefield, Optional[str])
    assert_type(doc.imagegridfsproxy, Optional[str])
    assert_type(doc.improperlyconfigured, Optional[str])
    assert_type(doc.imagefield, Optional[str])
    assert_type(doc.geopointfield, Optional[str])
    assert_type(doc.pointfield, Optional[str])
    assert_type(doc.linestringfield, Optional[str])
    assert_type(doc.polygonfield, Optional[str])
    assert_type(doc.sequencefield, Optional[str])
    assert_type(doc.uuidfield, Optional[str])
    assert_type(doc.enumfield, Optional[str])
    assert_type(doc.multipointfield, Optional[str])
    assert_type(doc.multilinestringfield, Optional[str])
    assert_type(doc.multipolygonfield, Optional[str])
    assert_type(doc.geojsonbasefield, Optional[str])
    assert_type(doc.decimal128field, Optional[str])
