class _ServerMode: ...
class Primary(_ServerMode): ...
class PrimaryPreferred(_ServerMode): ...
class Secondary(_ServerMode): ...
class SecondaryPreferred(_ServerMode): ...
class Nearest(_ServerMode): ...

class ReadPreference:
    NEAREST: Nearest
    PRIMARY: Primary
    PRIMARY_PREFERRED: PrimaryPreferred
    SECONDARY: Secondary
    SECONDARY_PREFERRED: SecondaryPreferred
