from mongoengine import document as md
from .queryset import QuerySetManager

class DjangoFlavor(object): ...

class Document(DjangoFlavor, md.Document): ...
class EmbeddedDocument(DjangoFlavor, md.EmbeddedDocument): ...
class DynamicDocument(DjangoFlavor, md.DynamicDocument): ...
