from mongoengine.document import Document
class QNodeVisitor: ...

class QNode:
    def to_query(self, document: Document) -> QNode: ...
    def accept(self, visitor: QNodeVisitor) -> QNode: ...


class Q(QNode):
    def __init__(self, **kwargs: object) -> None: ...
    def __or__(self, other: object) -> Q: ...
    def __and__(self, other: object) -> Q: ...

