from typing import Any, Dict, Iterable, Iterator, Mapping, MutableMapping, Tuple, Union

class SON(MutableMapping[str, Any]):
    def __init__(
        self, arg: Union[Mapping[str, Any], Iterable[Tuple[str, Any]]]
    ) -> None: ...
    def __getitem__(self, item: str) -> Any: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def to_dict(self) -> Dict[str, Any]: ...
    def __delitem__(self, v: Any) -> None: ...
    def __setitem__(self, k: str, v: Any) -> None: ...
